### ISSUE TITLE
Error With Quickstart Tutorial - Print url_for('profile'...) 

### ISSUE THREAD

**Issue by diek** [mitsuhiko/flask#1319]
From the Quickstart Tutorial, Running, print url_for('profile', username='John Doe') generates the following error.
-------
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/diek/.virtualenvs/flask_quickstart/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/diek/.virtualenvs/flask_quickstart/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/diek/.virtualenvs/flask_quickstart/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/Users/diek/.virtualenvs/flask_quickstart/lib/python2.7/site-packages/werkzeug/routing.py", line 1616, in build
    raise BuildError(endpoint, values, method)
werkzeug.routing.BuildError: ('profile', {'username': 'John Doe'}, None)

**Comment by diek** [comment]
My own mistake, a long day.
