### ISSUE TITLE
Flask-Mega Tutorial error

### ISSUE THREAD

**Issue by GillysWindows** [mitsuhiko/flask#1379]
Hi i am currently working through the Flask Mega-Tutorial and when i try to create a new user in part 4 (Databases) at the Play Time section i am getting the following errors and would appreciate any help in solving this issue --- I am extremely new to Linux, Python and Flask so apologise if ive overlooked something very simple here.
>>> u = models.User(nickname='john', email='john@email.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 2, in __init__
  File "/home/gilly/microblog/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/instrumentation.py", line 324, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/home/gilly/microblog/flask/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 725, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/gilly/microblog/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/instrumentation.py", line 158, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/home/gilly/microblog/flask/local/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 260, in __call__
    fn(*args, **kw)
  File "/home/gilly/microblog/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2693, in _event_on_first_init
    configure_mappers()
  File "/home/gilly/microblog/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2589, in configure_mappers
    mapper._post_configure_properties()
  File "/home/gilly/microblog/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1694, in _post_configure_properties
    prop.init()
  File "/home/gilly/microblog/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/interfaces.py", line 144, in init
    self.do_init()
  File "/home/gilly/microblog/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1549, in do_init
    self._process_dependent_arguments()
  File "/home/gilly/microblog/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1605, in _process_dependent_arguments
    self.target = self.mapper.mapped_table
  File "/home/gilly/microblog/flask/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 725, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/gilly/microblog/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1535, in mapper
    % (self.key, type(argument)))
sqlalchemy.exc.ArgumentError: relationship 'posts' expects a class or a mapper argument (received: <class 'sqlalchemy.sql.schema.Table'>)
>>> 
Thanks in advance for any help given.
Wayne.

**Comment by keyanp** [comment]
Hi @GillysWindows, I'm glad you've decided to use Flask. Unfortunately this issue tracker is meant for keeping track of bugs/documentation fixes/and new features for Flask and so we will have to close this, @untitaker. 

This kind of post is more suitable for somewhere like stackoverflow.com, our email list, or the IRC channel #pocoo. If you do use the IRC channel please send a link to a gist of your stack trace rather than posting it into the window. Thanks!

**Comment by GillysWindows** [comment]
Hi @Keyanp my apologies for posting in the wrong area i came to here from flask if i remember rightly sorry been to so many places searching for help aswell as looking at other things, i am well new to all this and i'm trying to run before i can walk lol, and sorry to sound stupid but " send a link to a gist of your stack trace " i have no idea what that means sorry :( could you possibly explain for me please and i will get IRC and join #pocoo and also goto stackoverflow as advised thanks and sorry again. Wayne.

**Comment by keyanp** [comment]
Hi @GillysWindows, no worries. By "send a link to..." I meant that instead of pasting that error output in the comments, or in the IRC channel, instead go here: https://gist.github.com/, paste your error in a window and then post the link instead. It just makes it easier to read :smile:

**Comment by GillysWindows** [comment]
Hi @Keyanp Thanks again i followed your link and advice again :) and will remember for future reference as no doubt i'll be doing this again shortly, cheers pal.

**Comment by keyanp** [comment]
@untitaker suggesting this be closed
