### ISSUE TITLE
PendingDeprecationWarning on use of import imp

### ISSUE THREAD

**Issue by johnthagen** [mitsuhiko/flask#1599]
Install flask:
``pip install flask``

If ``test.py`` contains:

```
import flask

```
A ``PendingDeprecationWarning`` is emitted:

``python  -Werror test.py``

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import flask
  File "C:\Users\John Hagen\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "C:\Users\John Hagen\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 28, in <module>
    from .config import ConfigAttribute, Config
  File "C:\Users\John Hagen\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\config.py", line 12, in <module>
    import imp
  File "C:\Users\John Hagen\AppData\Local\Programs\Python\Python35-32\lib\imp.py", line 33, in <module>
    PendingDeprecationWarning, stacklevel=2)
PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```

**Comment by lord63** [comment]
Possible duplicated as #1449, PR #1450 should fix this problem. Please try the fresh version on github.
