### ISSUE TITLE
When DEBUG=True, OSError: [Errno 88] Socket operation on non-socket

### ISSUE THREAD

**Issue by nerogit** [mitsuhiko/flask#1650]
I get `OSError: [Errno 88] Socket operation on non-socket` when I try to run the following app with debug enabled.  I am using Ubuntu 14.04.2 and Python 3.4.0.

```python
app = Flask(__name__)
app.debug = True

@app.route('/')
def index():
    return 'Hello, World!'

if __name__ == '__main__':
    app.run(host='0.0.0.0')
```
```
$ python app.py
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 916-262-145
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/nero/.virtualenvs/FBPocket/lib/python3.4/site-packages/gevent/threading.py", line 137, in run
    super(Thread, self).run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nero/.virtualenvs/FBPocket/lib/python3.4/site-packages/werkzeug/serving.py", line 653, in inner
    fd=fd).serve_forever()
  File "/home/nero/.virtualenvs/FBPocket/lib/python3.4/site-packages/werkzeug/serving.py", line 557, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/home/nero/.virtualenvs/FBPocket/lib/python3.4/site-packages/werkzeug/serving.py", line 478, in __init__
    self.server_address = self.socket.getsockname()
OSError: [Errno 88] Socket operation on non-socket
```

**Comment by nerogit** [comment]
Description:	Ubuntu 14.04.2 LTS
Release:	14.04

python 3.4.0

**Comment by davidism** [comment]
I can't reproduce your error.

This probably should be reported to Werkzeug instead, it seems similar to mitsuhiko/werkzeug#813.

**Comment by nerogit** [comment]
Sorry, I confirm it because of gevent. You can say that again. 
But I have same problem when run with gevent, I just do 
```python 
from gevent import monkey; monkey.patch_all()
```
with DEBUG=True. 
If I set DEBUG=False, that error is not appeared.

My pip freeze result is
```
Flask==0.10.1
gevent==1.1b5 
#May be it is reason of error. When I use python 2 with gevnet 1.0.2, that error is not appeard
greenlet==0.4.9
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
Werkzeug==0.11.2
wheel==0.24.0
```
like that.

Any way, I think this issue is not related with flask. Sorry again
