### ISSUE TITLE
Error running minitwit example

### ISSUE THREAD

**Issue by sdimitro** [mitsuhiko/flask#1652]
flask version is latest bleeding (from repo)
python version is 3.4 and OS is OpenBSD.

Traceback below:

```
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 9, in <module>
    load_entry_point('Flask==0.11.dev0', 'console_scripts', 'flask')()
  File "/usr/local/lib/python3.4/site-packages/flask/cli.py", line 494, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python3.4/site-packages/flask/cli.py", line 342, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/usr/local/lib/python3.4/site-packages/click/_unicodefun.py", line 69, in _verify_python3_env
    if locale.lower().endswith(('.utf-8', '.utf8')):
TypeError: 'str' does not support the buffer interface
```

**Comment by jianinz** [comment]
Hi @sdimitro have you got this problem solved? I am having the same issue, tried different approaches that were found online, still no success, wondering how you might get it working
