### ISSUE TITLE
AttributeError: module 'http.client' has no attribute 'get'

### ISSUE THREAD

**Issue by guoziyan** [mitsuhiko/flask#1681]
~~~python
Exception happened during processing of request from ('127.0.0.1', 52838)
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 344, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/Users/lxh/IdeaProjects/services/lib/python3.5/site-packages/werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/server.py", line 414, in handle
    self.handle_one_request()
  File "/Users/lxh/IdeaProjects/services/lib/python3.5/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    elif self.parse_request():
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/server.py", line 340, in parse_request
    conntype = self.headers.get('Connection', "")
~~~

**Comment by davidism** [comment]
Please include some code that reproduces this error.  See [mcve](http://stackoverflow.com/help/mcve).

**Comment by tash-had** [comment]
Hey @leaxoy , did you find a fix for this?
