### ISSUE TITLE
Flask resumes upload on restart

### ISSUE THREAD

**Issue by johnathanz** [mitsuhiko/flask#1693]
This may not be an Issue / Bug. But may be due to my newness to Flask & lack of understanding.

I'm running Flask on a Raspberry Pi (Raspbarian OS). There's PUT path set up to upload files to a certain directory.

During one of my test runs, I killed Flask using Ctrl-C.

Thereafter:
1) Start python program, which starts Flask - no issues
2) Calls the PUT Path to upload 3 files - no issues
3) After the 3 files are uploaded (from (2)), Flask attempts to resume on a file that was perhaps in progress when I first Ctrl-C the program. The file `TEST_0059.MP4` in this case

This is the immediate error message - occurs **everytime** after files are uploaded

    <path>/lib/python5.4/site-packages/werkzeug/filesystem.py:63: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii'
      BrokenFilesystemWarning)
    192.168.1.8 - - [13/Jan/2016 22:03:50] "PUT /uploadMedia/TEST_0059.MP4 HTTP/1.1" 500 -
    Traceback (most recent call last):
      File "<path>/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "<path>/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "<path>/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "<path>/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
        raise value
      File "<path>/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "<path>/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "<path>/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "<path>/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
        raise value
      File "<path>/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "<path>/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "<path>/cps_media_services.py", line 59, in to_hub_via_wifi
        f.write(request.data)
      File "<path>/lib/python3.4/site-packages/werkzeug/local.py", line 342, in __getattr__
        return getattr(self._get_current_object(), name)
      File "<path>/lib/python3.4/site-packages/werkzeug/utils.py", line 73, in __get__
        value = self.func(obj)
      File "<path>/lib/python3.4/site-packages/werkzeug/wrappers.py", line 446, in data
        return self.get_data(parse_form_data=True)
      File "<path>/lib/python3.4/site-packages/werkzeug/wrappers.py", line 477, in get_data
        rv = self.stream.read()
      File "<path>/lib/python3.4/site-packages/werkzeug/wsgi.py", line 1003, in read
        read = self._read(to_read)
    MemoryError

**Questions:**
* What's telling Flask to resume the PUT operation that I killed earlier?
* Doesn't restarting Flask clear any previous states it had?

**Comment by tkanoff** [comment]
An interesting issue. Could you please upload the full log starting from the first file upload right before the Ctrl+C?
Regarding what's telling Flask to resume - what do you use to actually make PUTs?

**Comment by davidism** [comment]
This doesn't sound like an error with Flask or Werkzeug.  Either the client sending the data, or the server receiving it is trying to resume the upload after a disconnection.  The error is just saying that it couldn't be completed, it doesn't prevent the app from running.  Closing, this needs more information about the issue, such as code to reproduce it, to consider reopening.

**Comment by vhosakot** [comment]
I saw the `BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem` error too. After digging the code, I saw that this error is harmless and just a warning in `/usr/local/lib/python2.7/dist-packages/werkzeug/filesystem.py`:

            warnings.warn(
                'Detected a misconfigured UNIX filesystem: Will use UTF-8 as '
                'filesystem encoding instead of {0!r}'.format(rv),
                BrokenFilesystemWarning)

So, I would not worry about the `BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem` warning.
