### ISSUE TITLE
TypeError: object.__new__(Markup) is not safe, use unicode.__new__() in specific cases

### ISSUE THREAD

**Issue by voidus** [mitsuhiko/flask#1700]
Hi,

I am currently struggling with a pretty weird bug. It only appears in specific situations. 

The whole code to reproduce it can be found in https://github.com/voidus/markupsafe_sniffer_issue or attached as 
[markupsafe_sniffer_issue.zip](https://github.com/mitsuhiko/markupsafe/files/102377/markupsafe_sniffer_issue.zip)

There has been an issue somewhat like that before but I can't find any encoding related problems.
https://github.com/mitsuhiko/markupsafe/issues/19

When I run a test via [sniffer](https://github.com/jeffh/sniffer), I get the following error every time except the first run. (Re-run can be triggered by touching e.g the application.py file)
```TypeError: object.__new__(Markup) is not safe, use unicode.__new__()```

I tried to debug that using pdb, but I cannot find any differences between runs. I also tried to minimize the problem by using jinja directly (see the second test), but that doesn't trigger the bug. As removing flask removes the bug, I'm posting this here. I have actually no Idea where the real problem is.

I'll also open an issue over at markupsafe linking here, so that the compined powers may find out what's wrong :)

Full Stack trace:
```
======================================================================
FAIL: test_application.test_application
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<redacted>/env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/<redacted>/tests/test_application.py", line 8, in test_application
    assert response.status_code == 200
AssertionError: 
-------------------- >> begin captured logging << --------------------
application: ERROR: Exception on / [GET]
Traceback (most recent call last):
  File "/<redacted>/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/<redacted>/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/<redacted>/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/<redacted>/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/<redacted>/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/<redacted>/application.py", line 7, in index
    return render_template('t.html', c="baz")
  File "/<redacted>/env/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/<redacted>/env/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/<redacted>/env/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/<redacted>/env/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/<redacted>/templates/t.html", line 1, in top-level template code
    <script src="{{c}}"></script>
  File "/<redacted>/env/src/markupsafe/markupsafe/__init__.py", line 75, in __new__
    return text_type.__new__(cls, base)
TypeError: object.__new__(Markup) is not safe, use unicode.__new__()
--------------------- >> end captured logging << ---------------------
```

**Comment by davidism** [comment]
Adding a print before `return text_type.__new__` in `markupsafe/__init__.py` shows that `text_type` is `unicode` for the first run, but is `None` when rendering variable nodes on subsequent runs.  The `"is not safe" error is actually [part of Python](http://stackoverflow.com/a/4028415/400617), but doesn't seem directly related, since the code isn't doing anything deliberately that is relevant to that error.

This appears to be a recurring issue with sniffer, see jeffh/sniffer#23 among others.  The common pattern is that something that shouldn't be `None` gets set to it on reload.  Sniffer is being clever to avoid starting a new Python process for each test run by [clearing `sys.modules`](https://github.com/jeffh/sniffer/blob/f51d6215164e923cbb64e4f5c4f2acd352ce32ea/sniffer/runner.py#L82-L83) and running nose from the same process.  This must be causing an issue somewhere within the import mechanism.  This does not seem like a good idea for testing, where you want to guarantee that each run is using the same starting point.

Using a Watchdog reloader, such as joeyespo/pytest-watch or joeyespo/nosey, which uses an efficient watcher but starts a new process for each run, does not have this issue.  Using Python 3 does not have this issue.

**Comment by davidism** [comment]
I'm closing this as an issue with sniffer.
