### ISSUE TITLE
nginx upstream check, but the access log is wrong.

### ISSUE THREAD

**Issue by staugur** [mitsuhiko/flask#1717]
**Some version information**

```
1. Tengine version: Tengine/2.1.2 (nginx/1.6.2)
2.CentOS6.7  python2.6
3.Flask Version: 0.10.1
```

**Nginx configuration file content:**
```
    upstream weibo {
        ip_hash;
        server 127.0.0.1:7076;
        check interval=3000 rise=2 fall=5 timeout=1000 type=http;
        #check_http_expect_alive http_2xx http_3xx ;
        check_http_send "GET / HTTP/1.0\r\n\r\n";
    }
    server {
        listen 80;
        client_max_body_size 50M;
        server_name weibo.saintic.com;
        location / {
            proxy_pass_header Server;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
            proxy_pass http://weibo;
        }
        location /nstatus {
           check_status;
           access_log off;
        }
    }
```

**My flask app(https://github.com/saintic/ULR/blob/master/ulr.py)**

**Access log error:**

```
127.0.0.1 - - [04/Feb/2016 17:24:54] "GET / HTTP/1.0" 302 -
Traceback (most recent call last):
  File "/usr/lib64/python2.6/SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.6/SocketServer.py", line 319, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.6/SocketServer.py", line 332, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.6/SocketServer.py", line 628, in __init__
    self.finish()
  File "/usr/lib64/python2.6/SocketServer.py", line 671, in finish
    self.wfile.flush()
  File "/usr/lib64/python2.6/socket.py", line 303, in flush
    self._sock.sendall(buffer(data, write_offset, buffer_size))
error: [Errno 32] Broken pipe
```

**Comment by ThiefMaster** [comment]
You are not supposed to use the dev server (`app.run()`) in production.

**Comment by staugur** [comment]
This method(app.run()) is only used in the development of the environment?

Production environment must be deployed in the following ways?
http://www.pythondoc.com/flask/deploying/index.html

**Comment by staugur** [comment]
sorry, the url is http://flask.pocoo.org/docs/0.10/deploying/

**Comment by ThiefMaster** [comment]
so what is the actual problem? the "broken pipe"? it just means that the client closed the connection early

**Comment by staugur** [comment]
What an embarrassing question!
I will check the solution from Google.Just don't want it to appear.

**Comment by ThiefMaster** [comment]
It's the dev server, you can simply ignore the exception

**Comment by staugur** [comment]
Thank you very much！
