### ISSUE TITLE
Problem with sending form with enctype="multipart/form-data".

### ISSUE THREAD

**Issue by Delyo** [mitsuhiko/flask#679]
I am using Flask 0.8 on developing server WAMP.
On production server I have no problem uploading images. But when I send the form to the localhost I get ClientDisconnected: 400: Bad Request.

It is enough just to have the enctype="multipart/form-data" atribute to get the error, doesn't matter if there is a file uploaded or not. Wnen I try to get request.form or request.files I get error.

I tested to upload with PHP on the same server and it works. There must be something between Flask and WAMP.

---
The imports:

from flask import Flask, request, session, g, redirect, url_for, abort, render_template, flash, _request_ctx_stack, current_app, get_flashed_messages
from werkzeug import secure_filename

----
The handler:

@app.route('/upload', methods=['GET', 'POST'])
@requires_admin
def upload():
 if request.method == 'POST':
  id = request.form['id']
  img = request.files['img']
  ...

----
The traceback:

Traceback (most recent call last):
File "C:/wamp/www/zaemide/main.py", line 203, in edit
form = request.form.copy()
File "C:\wamp\www\vedacon\werkzeug\local.py", line 336, in __getattr__
return getattr(self._get_current_object(), name)
File "C:\wamp\www\vedacon\werkzeug\utils.py", line 77, in __get__
value = self.func(obj)
File "C:\wamp\www\vedacon\werkzeug\wrappers.py", line 383, in form
self._load_form_data()
File "C:\wamp\www\vedacon\flask\wrappers.py", line 119, in _load_form_data
RequestBase._load_form_data(self)
File "C:\wamp\www\vedacon\werkzeug\wrappers.py", line 318, in _load_form_data
data = parser.parse_from_environ(self.environ)
File "C:\wamp\www\vedacon\werkzeug\formparser.py", line 164, in parse_from_environ
return self.parse(stream, mimetype, content_length, options)
File "C:\wamp\www\vedacon\werkzeug\formparser.py", line 188, in parse
content_length, options)
File "C:\wamp\www\vedacon\werkzeug\formparser.py", line 100, in wrapper
stream.exhaust()
File "C:\wamp\www\vedacon\werkzeug\wsgi.py", line 782, in exhaust
self.read(chunk)
File "C:\wamp\www\vedacon\werkzeug\wsgi.py", line 800, in read
return self.on_disconnect()
File "C:\wamp\www\vedacon\werkzeug\wsgi.py", line 768, in on_disconnect
raise ClientDisconnected()
ClientDisconnected: 400: Bad Request

Thanks!

**Comment by keyanp** [comment]
@Delyo Was this resolved by simply upgrading? Or do we still need to address this?

**Comment by keyan** [comment]
It seems that upgrading was sufficient to resolve this problem and perhaps this was an issue with @Delyo's application code.
